server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: blog-admin

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
